[project]
name = "xai-aws-bedrock"
version = "0.1.0"
description = "A Xircuits component library for the AWS bedrock APIs"
authors = [{ name = "XpressAI", email = "eduardo@xpress.ai" }]
license = "MIT"
readme = "README.md"
repository = "https://github.com/XpressAI/xai-aws-bedrock"
keywords = ["xircuits", "bedrock", "text generation"]

# Xircuits-specific configurations
[tool.xircuits]
default_example_path = "bedrock_example.xircuits"
requirements_path = "requirements.txt"
